"""
app/api/v1/keys.py
------------------
API key management endpoints.
"""
from __future__ import annotations

import uuid
from fastapi import APIRouter, Depends

from app.core.deps import get_current_user
from app.db.session import AsyncSessionLocal
from app.models.user import User
from app.schemas.auth import MessageResponse
from app.schemas.keys import APIKeyCreatedResponse, APIKeyResponse, CreateAPIKeyRequest
from app.services.key_service import KeyService

router = APIRouter(prefix="/keys", tags=["API Keys"])


@router.post("", response_model=APIKeyCreatedResponse, status_code=201)
async def create_api_key(
    body: CreateAPIKeyRequest,
    current_user: User = Depends(get_current_user),
) -> APIKeyCreatedResponse:
    """
    Generate a new API key.
    The raw key is returned ONLY once in this response.
    Save it securely as it cannot be retrieved again.
    """
    async with AsyncSessionLocal() as db:
        service = KeyService(db)
        api_key, raw_key = await service.create_key(current_user.id, body.name)
        
        return APIKeyCreatedResponse(
            id=api_key.id,
            name=api_key.name,
            raw_key=raw_key,
            created_at=api_key.created_at,
        )


@router.get("", response_model=list[APIKeyResponse])
async def list_api_keys(
    current_user: User = Depends(get_current_user),
) -> list[APIKeyResponse]:
    """List all API keys generated by the authenticated user."""
    async with AsyncSessionLocal() as db:
        service = KeyService(db)
        keys = await service.list_keys(current_user.id)
        return [APIKeyResponse.model_validate(k) for k in keys]


@router.delete("/{key_id}", response_model=MessageResponse)
async def deactivate_api_key(
    key_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
) -> MessageResponse:
    """Deactivate (revoke) an API key. Once revoked, the key cannot be used."""
    async with AsyncSessionLocal() as db:
        service = KeyService(db)
        await service.deactivate_key(current_user.id, key_id)
        return MessageResponse(message="API key deactivated successfully.")
